### PR TITLE
Justin01010-lab1-attempt1

### PR DESCRIPTION
**Pull request by justin01010**
---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to TA's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

### CODE REVIEW

**Comment by 13579and2468** [comment]
目錄位置不太對，所以測資跑不起來，可以參考投影片的方法下載作業

**Comment by justin01010** [comment]
> 目錄位置不太對，所以測資跑不起來，可以參考投影片的方法下載作業

**Comment by justin01010** [comment]
助教您好，我上星期四有上傳attempt2了，再麻煩您幫我確認一下，謝謝！

**Comment by 13579and2468** [comment]
我後來有看到了，沒問題~

justin01010 ***@***.***> 於 2021年9月28日 週二 15:43 寫道：

**Comment by justin01010** [comment]
好的，謝謝助教！

**Pull request closed without merging**
