### PR TITLE
fgjyh-lab2-attempt2

### PR DESCRIPTION
**Pull request by fgjyh**
---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to TA's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

### CODE REVIEW

**Comment by benchen216** [comment]
Not correct

**Comment by fgjyh** [comment]
請問問題出在哪?

**Comment by benchen216** [comment]
Screen Shot 2021-09-30 at 9 12 16 PM
test case 2不正確

**Comment by fgjyh** [comment]
Done

**Pull request closed without merging**
